### PR TITLE
Add Streams support for AllDebrid

### PR DESCRIPTION
**Pull request by the-honey**
Closes: #4

### CODE REVIEW

**Comment by MrMonkey42** [comment]
@the-honey Thank you for the PR !

**Comment by the-honey** [comment]
You should update the issue on [danamag/stremio-addons-list](https://github.com/danamag/stremio-addons-list/issues/226) as well.

**Comment by MrMonkey42** [comment]
What update are you referring to? The version details would be updated automatically

**Comment by Mahmoud23go** [comment]
hESnBRk67VGwI0dL7IsV295HOxRyUE3thdiH

**Pull request merged**
